// Todo app
export const GET_TODO_SUCCESS = "todo/get/success"
export const GET_TODO_LOADING = "todo/get/loading"
export const GET_TODO_ERROR = "todo/get/error"
export const ADD_TODO_SUCCESS = "todo/add/success"
export const ADD_TODO_LOADING = "todo/add/loading"
export const ADD_TODO_ERROR = "todo/add/error"
export const COMPLETE_TODO = "todo/complete"
export const UPDATE_TODO = "todo/update"
export const DELETE_TODO = "todo/delete"